model_name: SVHF
model: SVHF

load_model: True
res_ckpt_path: /home/fz/2-VF-feature/JVF-net/saved/Resnet/2021-May-26:18:04/resnet-epoch-60.pth
pase_cfg_path:  /home/fz/2-VF-feature/PASE/cfg/frontend/PASE.cfg  # not the files  /home/fz/2-VF-feature/PASE/cfg/frontend/PASE.cfg
pase_ckpt_path: /home/fz/2-VF-feature/PASE/saved_model/RAVDESS_ckpt/2021-May-22:11:00/FE_e+800.ckpt   # not the files

voice_data_root: /home/fz/2-VF-feature/JVF-net/dataset/RAVDESS/2 wave-Actor1-24-16k
voice_data_cfg: /home/fz/2-VF-feature/JVF-net/dataset/RAVDESS/RAVDESS_voice_data.cfg
face_data_root: /home/fz/2-VF-feature/JVF-net/dataset/RAVDESS/1 image-Actor1-24
face_data_cfg: /home/fz/2-VF-feature/JVF-net/dataset/RAVDESS/RAVDESS_image_data.cfg

voice_batch_size: 16
face_batch_size: 24
num_workers: 8

lr: 0.001
epoch: 2000
lr_decay_factor: 0.1
patience: 1
weight_init: kaiming_uniform
optim: Adam

val_every: 1
save_every: 1
val_sample_dir: ./val_sample
save_path: ./saved/JVF-net/

tensorboard: True
multi_gpu: False
gpu_ids:
    - 0
    - 1